version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
azurelib = true
toastysmobs = true
farmersdelight = true
where_winds_blow = true
simplyswords = true
create = true
stellaris = false
aeronautics = true
interiors = true
simulated = true
estrogen = true
etched = true
cataclysm = true
sable_player_ragdoll = true
easyanvils = true
createoreexcavation = true
visualworkbench = true
createestrogen = true
ntgl = true
minecraft = true
create_dragons_plus = true
comforts = true
create_connected = true
irons_lib = true
create_enchantment_industry = true
trading_floor = true
create_things_and_misc = true
create_sa = true
railways = true
bellsandwhistles = true
aquaculturedelight = true
irons_patreon_lib = true
ftbquests = true
block_factorys_bosses = true
moonlight = true
sophisticatedbackpacks = true
alloyed = true
create_aquatic_ambitions = true
offroad = true
create_power_loader = true
creategoggles = true
dndesires = true
